#!/usr/bin/env python3
"""
Example: Community-Acquired Pneumonia Recommendation

This script demonstrates how to use the BAA-2025 system to generate
an antibiotic recommendation for a patient with CAP.
"""

import sys
sys.path.insert(0, '/home/user/googleaiantibioteka')

from app.models.patient import Patient, PatientDemographics, PhysiologicalParameters
from app.models.infection import InfectionProfile, InfectionSite, InfectionAcquisition, InfectionSeverity
from app.services.drug_registry import DrugRegistry
from app.services.clinical_decision_engine import ClinicalDecisionEngine
from config.config import Config


def main():
    """Generate CAP recommendation example"""

    # Initialize services
    registry = DrugRegistry(Config.REGISTRY_PATH)
    engine = ClinicalDecisionEngine(registry)

    # Define patient: 35-year-old male with moderate CAP
    patient = Patient(
        demographics=PatientDemographics(
            age_years=35,
            gender="male",
            weight_kg=75,
            height_cm=175
        ),
        physiology=PhysiologicalParameters(
            serum_creatinine_mg_dl=1.0
        ),
        allergies=[],
        is_hospitalized=False
    )

    # Define infection: Moderate CAP
    infection = InfectionProfile(
        site=InfectionSite.CAP,
        acquisition=InfectionAcquisition.COMMUNITY,
        severity=InfectionSeverity.MODERATE,
        fever_present=True,
        max_temperature_c=38.5,
        duration_days=2
    )

    print("=" * 80)
    print("BAA-2025: Bosnia & Herzegovina Antibiotic Advisor")
    print("=" * 80)
    print()
    print("PATIENT INFORMATION:")
    print(f"  Age: {patient.demographics.age_years} years")
    print(f"  Gender: {patient.demographics.gender}")
    print(f"  Weight: {patient.demographics.weight_kg} kg")
    print(f"  CrCl: {patient.calculate_creatinine_clearance()} mL/min")
    print()
    print("INFECTION PROFILE:")
    print(f"  Site: {infection.site}")
    print(f"  Severity: {infection.severity}")
    print(f"  MDR Risk: {infection.calculate_mdr_risk()}")
    print()
    print("=" * 80)
    print("GENERATING RECOMMENDATION...")
    print("=" * 80)
    print()

    # Generate recommendation
    prescription = engine.generate_recommendation(patient, infection)

    # Display recommendation
    print("CLINICAL ASSESSMENT:")
    print(f"  {prescription.clinical_assessment}")
    print()
    print("DIAGNOSIS:")
    print(f"  {prescription.diagnosis}")
    print()
    print("SEVERITY ASSESSMENT:")
    print(f"  {prescription.severity_assessment}")
    print()
    print("=" * 80)
    print("PRIMARY RECOMMENDATION:")
    print("=" * 80)

    primary = prescription.primary_recommendation
    print(f"Drug: {primary.generic_name}")
    print(f"Brands: {', '.join(primary.trade_names)}")
    print(f"Formulation: {primary.formulation}")
    print(f"Route: {primary.route}")
    print()
    print("DOSING:")
    print(f"  Dose: {primary.dose_calculation.dose_amount} {primary.dose_calculation.dose_unit}")
    print(f"  Frequency: {primary.dose_calculation.frequency}")
    print(f"  Duration: {primary.dose_calculation.duration_days} days")
    print(f"  Total Daily Dose: {primary.dose_calculation.total_daily_dose} {primary.dose_calculation.dose_unit}")
    print()
    print("REGULATORY STATUS:")
    print(f"  Status: {primary.regulatory_status}")
    print(f"  Prescription Type: {primary.prescription_type}")
    print()
    print("CLINICAL RATIONALE:")
    print(f"  {primary.rationale}")
    print()
    print("PATHOGEN COVERAGE:")
    for pathogen in primary.coverage:
        print(f"  - {pathogen}")
    print()
    print("PRESCRIPTION INSTRUCTIONS:")
    print(f"  {primary.prescription_instructions}")
    print()
    print("PATIENT COUNSELING:")
    print(f"  {primary.patient_instructions}")
    print()

    if prescription.alternative_recommendations:
        print("=" * 80)
        print("ALTERNATIVE OPTIONS:")
        print("=" * 80)
        for i, alt in enumerate(prescription.alternative_recommendations, 1):
            print(f"\n{i}. {alt.generic_name} ({', '.join(alt.trade_names)})")
            print(f"   Indication: {alt.indication}")
            print(f"   Reason: {alt.reason_for_alternative}")
            print(f"   Dose: {alt.dose_calculation.dose_amount} {alt.dose_calculation.dose_unit} {alt.dose_calculation.frequency}")

    print()
    print("=" * 80)
    print("FOLLOW-UP:")
    print("=" * 80)
    print(f"Reassessment: {prescription.reassessment_timing}")
    print(f"Cultures: {prescription.culture_guidance}")
    print()
    print("BiH AVAILABILITY: ✓ Confirmed in Registar lijekova 2025")
    print()
    print("=" * 80)
    print("This recommendation generated by BAA-2025 deterministic engine")
    print("No hallucinations - Only BiH-registered drugs recommended")
    print("=" * 80)


if __name__ == "__main__":
    main()
